---
title: "flat_my_fun.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# get_welcome_message_pierre
```{r}
date <- as.Date("23/01/2023", "%d/%m/%Y") 

if((inherits(date, "Date")==TRUE)){
  message(paste("Hey ! Nous sommes le", as.character(date), ", c'est un super jour pour aller observer les écurueils, non ?" ))} else{
    stop("La date indiquée n'est pas au format date")}

```


```{r function-get_welcome_message_pierre}
#' my_fun get_welcome_message_pierre
#'
#'Renvoie un message avec une date entrée par l'utilisateur
#'
#' @param date une date au format date
#'
#' @return Un message ou une erreur
#' @export
#'
#' @examples
get_welcome_message_pierre <- function(date) {
  if((inherits(date, "Date")==TRUE)){
  message(paste("Hey ! Nous sommes le", as.character(date), ", c'est un super jour pour aller observer les ecurueils, non ?" ))} else{
    stop("La date indiquee n'est pas au format date")
  }
}
```

```{r examples-get_welcome_message_pierre}
get_welcome_message_pierre(as.Date("23/01/2023", "%d/%m/%Y"))
```

```{r tests-get_welcome_message_pierre}

test_that("my_fun works", {
 expect_message(
   object=get_welcome_message_pierre(as.Date("23/01/2023", "%d/%m/%Y")),
   regexp="Hey ! Nous sommes le 2023-01-23 , c'est un super jour pour aller observer les ecurueils, non ?"
 )
})

test_that("my_fun works2", {
 expect_error(get_welcome_message_pierre(2323))
})
expect_error()

```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_my_fun.Rmd", vignette_name = "get_welcome_message_pierre", overwrite = TRUE, open_vignette = FALSE)
```

