# WARNING - Generated by {fusen} from dev/flat_get_message.Rmd: do not edit by hand

# test_that("get_message_paul return Error", {

# # erreur : ce n'est pas un format character
# expect_error(
#   is.numeric(date),
#   "date n'est pas un numérique")
# get_message_paul(26/01/2023)
# })
