# WARNING - Generated by {fusen} from dev/flat_get_welcome_message_benoit.Rmd: do not edit by hand

test_that("get_welcome_message_benoit works", {
  expect_message(get_welcome_message_benoit("06/06/2024"), "Hey ! Nous sommes le 06/06/2024, c'est un super jour pour aller observer les ecureuils, non ?")

})

