# WARNING - Generated by {fusen} from dev/flat_get_welcome_message_raul.Rmd: do not edit by hand

test_that("get_welcome_message_raul works", {
  expect_error(get_welcome_message_raul(date="a"))
  expect_error(get_welcome_message_raul(date="1"))
  expect_equal(get_welcome_message_raul(date = "23/01/2023"), "Hey ! Nous sommes le 23/01/2023 c'est un super jour pour aller observer les écurueils, non ?")
  
})
