# WARNING - Generated by {fusen} from dev/flat_read_multiple_data.Rmd: do not edit by hand

test_that("read_multiple_data works", {

  
    expect_error(
      read_multiple_data(path = "jenexistepas"),
      "path does not exist"
    )
  
  
  tmp_dir <- tempfile(pattern = "toto")
  dir.create(tmp_dir)
  expect_error(
    read_multiple_data(path = tmp_dir),
    "There is no files in this path"
  )
  
  file.copy(
    from = list.files(
      system.file(package = "squirrels"),
      pattern = "nyc_squirrels_[0-9][0-9].xlsx",
      full.names = TRUE
    ),
    to = tmp_dir
  )
  res_import_xlsx <- read_multiple_data(tmp_dir)

  expect_equal(
    length(res_import_xlsx),
    4
  )

  
})
