# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand


test_that("my_fun works", {
 expect_message(
   object=get_welcome_message_pierre(as.Date("23/01/2023", "%d/%m/%Y")),
   regexp="Hey ! Nous sommes le 2023-01-23 , c'est un super jour pour aller observer les ecurueils, non ?"
 )
})

test_that("my_fun works2", {
 expect_error(get_welcome_message_pierre(2323))
})
expect_error()

