# WARNING - Generated by {fusen} from dev/flat_get_welcome_message.Rmd: do not edit by hand

test_that("get_welcome_message returns the correct message for a given date in day/month/year format", {
  date_example <- "06/06/2024"
  expected_message <- "Hey! Nous sommes le 06/06/2024, c'est un super jour pour aller observer les écureuils non?"
  expect_equal(get_welcome_message(date_example), expected_message)
})



