# WARNING - Generated by {fusen} from dev/flat_run_analysis.Rmd: do not edit by hand

test_that("run_analysis works with client data", {
  output_dir <- tempfile()
  dir.create(output_dir)

  data <- readxl::read_excel(
    system.file("nyc_squirrels_client_file_to_be_used_as_reference.xlsx", package = "squirrels")
  )
  run_analysis(data, output_dir)

  expect_true(file.exists(file.path(output_dir, "valid_data.csv")))
  expect_true(file.exists(file.path(output_dir, "invalid_data.csv")))
  expect_true(file.exists(file.path(output_dir, "missing_data.csv")))

  valid_data <- read.csv2(file.path(output_dir, "valid_data.csv"))

  expect_equal(
    nrow(valid_data),
    362
  )

  invalid_data <- read.csv2(file.path(output_dir, "invalid_data.csv"))
  expect_equal(
    nrow(invalid_data),
    6
  )

  missing_data <- read.csv2(file.path(output_dir, "missing_data.csv"))
  expect_equal(
    nrow(missing_data),
    4
  )
  unlink(output_dir, recursive = TRUE)
})
