# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand

#' my_fun get_welcome_message_pierre
#'
#'Renvoie un message avec une date entrée par l'utilisateur
#'
#' @param date une date au format date
#'
#' @return Un message ou une erreur
#' @export
#'
#' @examples
#' get_welcome_message_pierre(as.Date("23/01/2023", "%d/%m/%Y"))
get_welcome_message_pierre <- function(date) {
  if((inherits(date, "Date")==TRUE)){
  message(paste("Hey ! Nous sommes le", as.character(date), ", c'est un super jour pour aller observer les ecurueils, non ?" ))} else{
    stop("La date indiquee n'est pas au format date")
  }
}
