# WARNING - Generated by {fusen} from dev/flat_get_message.Rmd: do not edit by hand

#' my_fun Title
#'
#' @param date une date au format character 
#' @importFrom stringr str_c
#' @return un message
#' @export
#'
#' @examples 


#' # get_message_paul()
#' # get_message_paul("26/01/2023")
#'
get_message_paul <- function(date = NULL) {
  
  if(is.null(date)){date = "23/01/2023"}
  
  if (isFALSE(is.character(date))){stop("la date n'est pas renseignu262Fe au format \"DD/MM/YYYY\"")}
  
  message <- (stringr::str_c("Hey ! Nous sommes le ",date," c'est un super jour pour aller observer les u262Fcureuils, non ?"))
  cat(message)
}
