# WARNING - Generated by {fusen} from dev/flat_get_welcome_message.Rmd: do not edit by hand

#' Envoie un message de bienvenue avec la date choisie par l'utilisateur
#'
#' @param date character qui prend la forme %d/%m/%y
#' @importFrom glue glue
#' @return glue character
#' @export
#'
#' @examples
#' date_ok <- "01/12/2023"
#' get_welcome_message(date_ok)
get_welcome_message <- function(date) {
date_param <- date
  if (!grepl("^\\d{2}/\\d{2}/\\d{4}$", date_param)) {
    stop("La date doit etre au format jour/mois/annee (dd/mm/yyyy)")
  }
  
  welcome <- glue("Hey! Nous sommes le {date_param}, c'est un super jour pour aller observer les écureuils non?")
  return(welcome)
}
