# WARNING - Generated by {fusen} from dev/flat_get_welcome_message_benoit.Rmd: do not edit by hand

#' get_welcome_message_benoit 
#' 
#' Benoit's function to send a welcome message to the user.
#'
#' @param date A `string` character providing the date to be included in the welcome message.
#' @importFrom glue glue
#' @return A message in the console welcoming the user with the provided `date` parameter.
#' @export
#'
#' @examples
#' get_welcome_message_benoit("02/01/1997")
#'
get_welcome_message_benoit <- function(date) {
welcome_message <- glue("Hey ! Nous sommes le {date}, c'est un super jour pour aller observer les ecureuils, non ?")
message(welcome_message)
}
