# WARNING - Generated by {fusen} from dev/flat_get_welcome_message_raul.Rmd: do not edit by hand

#' get_welcome_message_raul Title
#'
#' @param date a character string that looks like a date
#'
#' @importFrom stringr str_replace_all
#' @return A message
#' @export 
#'
#' @examples




#' get_welcome_message_raul()
#' get_welcome_message_raul(date="09/02/1982")
#'
get_welcome_message_raul <- function(date=stringr::str_replace_all(Sys.Date(), "-", "/")) {
  
  if (isFALSE(inherits(as.Date(date),"Date"))){
    stop()
  }
  
  return(print(paste0("Hey ! Nous sommes le ", date," c'est un super jour pour aller observer les écurueils, non ?"))
)
  
}
