# WARNING - Generated by {fusen} from dev/flat_read_multiple_data.Rmd: do not edit by hand

#' read_multiple_data Title
#'
#' @param path le chemin
#' @importFrom stringr str_extract str_sub
#' @importFrom readxl read_excel
#' @importFrom purrr possibly map set_names
#' @return une liste de fichiers lus
#' @export
#'
#' @examples
#' library(purrr)
#' tabs <- read_multiple_data(path = system.file(package = "squirrels"))
#'
#'
#' ttt <- tabs |>
#'   map(nrow)
#'
#' unlist(ttt["19"])
#'
#' ttt["19"]
#' ttt[["19"]]
#'
#'
#' tabs |>
#'   compact() |>
#'   map(nrow)
#'
read_multiple_data <- function(path) {
  
  if (isFALSE(dir.exists(path))) {
    stop("path does not exist")
  }
  
  
  possi_excel <- possibly(read_excel, otherwise = NULL)
    
  chemin <- list.files(path = path, 
                       pattern = "nyc_squirrels_[0-9][0-9].xlsx", 
                       full.names = TRUE )
  
  
  if (length(chemin) == 0){
    stop("There is no files in this path")
  }
  
  annee <- stringr::str_extract(chemin, pattern = "[0-9][0-9].xlsx") |>
            stringr::str_sub(1,2)
  
  resultat <- chemin |>
    map(possi_excel) |>
    set_names(annee)
  
  return(resultat)
}
